name: Build EFC Schema Loader Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - "plugin-v*"

jobs:
  build-plugin-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create plugin ZIP
        run: |
          cd wp-content/plugins
          zip -r efc-schema-loader.zip efc-schema-loader

      - name: Upload plugin ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: efc-schema-loader
          path: wp-content/plugins/efc-schema-loader.zip
