name: Build all papers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Install Python deps
        run: |
          python3 -m pip install --upgrade pip
          pip install requests python-slugify

      - name: Build all papers
        run: |
          python3 efc_full_sync/tools/efc_full_sync_multibuilder.py

      - name: Commit package (including PDF)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name  "GitHub Actions"

          git add docs/papers/efc/*/* || true
          git add papers_src/*/* || true

          git commit -m "Auto: update all EFC papers and formal package" || echo "No changes"

          # Resolve binary merge conflicts automatically
          git pull --strategy=ours --no-edit origin main || true

          git push
